[package]
name = "supernova"
version = "0.1.0"
authors = [ "Jules de Smit <julesdesmit@gmail.com>" ]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
bellman = "0.13.1"
ff = "0.12.0"
halo2curves = { git = 'https://github.com/privacy-scaling-explorations/halo2curves', tag = '0.3.0' }
poseidon = { git = "https://github.com/privacy-scaling-explorations/poseidon" }
